# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.16.3]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Before script
              run: export NODE_OPTIONS=--max_old_space_size=4096

            - name: Install dependencies and build
              run: |
                  node common/scripts/install-run-rush.js install
                  node common/scripts/install-run-rush.js rebuild --verbose

            - name: Install Azure CLI
              run: |
                  AZ_REPO=$(lsb_release -cs)
                  echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
                  curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
                  sudo apt-get update
                  sudo apt-get install apt-transport-https azure-cli

            - name: Deploy to azure
              run: bash ./common/scripts/deploy-to-azure.sh
